<?php
/** @var Brideo\Magento2Scaffolding\Block\File $block */
echo '<?php'
?>


namespace <?php echo $block->NamespaceModule() ?>\Model\ResourceModel\<?php echo $block->getData('class_name') ?>;

/**
 * Class Collection
 *
 * @method <?php echo $block->NamespaceModule() ?>\Model\ResourceModel\<?php echo $block->getData('class_name') ?> _getResource()
 *
 * @package <?php echo $block->NamespaceModule() ?>\Model\ResourceModel\<?php echo $block->getData('class_name') ?>

 */
class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{

    /**
     * @var string
     */
    protected $_idFieldName = 'entity_id';

    /**
     * Define the resource model & the model.
     *
     * @return $this
     */
    protected function _construct()
    {
        $this->_init('<?php echo $block->NamespaceModule() ?>\Model\<?php echo $block->getData('class_name') ?>', '<?php echo $block->NamespaceModule() ?>\Model\ResourceModel\<?php echo $block->getData('class_name') ?>');

        return $this;
    }

}
