<?php
/** @var Brideo\Magento2Scaffolding\Block\File $block */
?>
{
  "name": "<?php echo strtolower($this->getData('namespace')) ?>/<?php echo strtolower($this->getData('module')) ?>",
  "description": "",
  "type": "magento2-module",
  "version": "<?php echo $this->getData('version') ?>",
  "license": [
    "Commercial"
  ],
  "repositories": {
    "magento": {
      "type": "composer",
      "url": "https://repo.magento.com/"
    }
  },
  "require": {
    "magento/framework": "100.0.*"
  },
  "autoload": {
    "files": [
      "src/registration.php"
    ],
    "psr-4": {
      "<?php echo $this->getData('namespace') ?>\\<?php echo $this->getData('module') ?>\\": "src"
    }
  }
}
