<?php  /** @var Brideo\Magento2Scaffolding\Block\File $block */ ?>
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:App/etc/routes.xsd">
    <router id="admin">
        <route id="<?php echo $block->namespace_module() ?>" frontName="<?php echo $block->namespace_module() ?>">
            <module name="<?php echo $block->namespace_module(false) ?>" before="Magento_Backend" />
        </route>
    </router>
</config>
