<?php
/** @var Brideo\Magento2Scaffolding\Block\File $block */
?>
<?php echo '<?php' ?>

/** @var \<?php echo $block->NamespaceModule() ?> \Block\<?php echo $block->getData('block_name'); ?> $block */

<?php echo '?>' ?>

<?php echo

'<?php /** @var \Brideo\Example\Block\Blog $block */ ?>

<?php foreach ($block->getCollection() as $item): ?>
    <?php foreach ($item as $key => $value): ?>
        <h2><?php echo $key ?></h2>
        <p><?php echo $value ?></p>
    <?php endforeach; ?>
<?php endforeach; ?>
'; ?>
