<?php
/** @var Brideo\Magento2Scaffolding\Block\File $block */
echo '<?php'
?>


namespace <?php echo $block->NamespaceModule() ?>\Observer;

use Magento\Framework\Event\ObserverInterface;
use Magento\Framework\View\LayoutInterface;

/**
 * Class <?php echo $block->getData('class_name') ?>
 *
 * @package <?php echo $block->NamespaceModule() ?>\Observer
 */
class <?php echo $block->getData('class_name') ?> implements ObserverInterface
{

    /**
     * Observe an event.
     *
     * @param Observer $observer
     * @event <?php echo $block->getData('event_name') ?>
     *
     * @return void
     */
    public function execute(\Magento\Framework\Event\Observer $observer)
    {
        //TODO: Perform Observer logic
    }

}
