<?php
/** @var Brideo\Magento2Scaffolding\Block\File $block */
echo '<?php'
?>


namespace <?php echo $block->NamespaceModule() ?>\Setup;

use Magento\Framework\Setup\InstallSchemaInterface;
use Magento\Framework\Setup\ModuleContextInterface;
use Magento\Framework\Setup\SchemaSetupInterface;
use Magento\Framework\DB\Ddl\Table;

class InstallSchema implements InstallSchemaInterface
{
    /**
     * Installs DB schema for a module
     *
     * @param SchemaSetupInterface $setup
     * @param ModuleContextInterface $context
     *
     * @return void
     */
    public function install(SchemaSetupInterface $setup, ModuleContextInterface $context)
    {
        $installer = $setup;

        $installer->startSetup();

        $table = $installer->getConnection()
            ->newTable($installer->getTable('<?php echo $block->table_name() ?>'))
            ->addColumn(
                'entity_id',
                Table::TYPE_SMALLINT,
                null,
                ['identity' => true, 'nullable' => false, 'primary' => true],
                'Entity ID'
            );

    <?php foreach($block->getData('columns') as $tableName => $type): ?>
    $table->addColumn('<?php echo $tableName ?>', <?php echo $block->TableType($type) ?>);
    <?php endforeach; ?>

        $installer->getConnection()->createTable($table);
        $installer->endSetup();
    }

}
