<?php
/** @var Brideo\Magento2Scaffolding\Block\File $block */

/**
 * Dirty helper function.
 *
 * @param \Brideo\Magento2Scaffolding\Block\File $block
 *
 * @return string
 */
function getName(Brideo\Magento2Scaffolding\Block\File $block) {
    return strtolower($block->getData('namespace') . '_' . $block->getData('module') . '_' . $block->getData('front_name') . '_' . $block->getData('action_name'));
}

/**
 * Dirty helper function.
 *
 * @param \Brideo\Magento2Scaffolding\Block\File $block
 *
 * @return string
 */
function getTemplate(Brideo\Magento2Scaffolding\Block\File $block) {
    return $block->getData('namespace') . '_' . $block->getData('module').'::'.strtolower($block->getData('front_name') . '/' . $block->getData('action_name')) .'.phtml';
}

?>
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <referenceContainer name="content">
        <block class="Magento\Framework\View\Element\Template" name="<?php echo getName($block) ?>" template="<?php echo getTemplate($block) ?>" />
    </referenceContainer>
</page>
